# Generated by Django 5.2.17 on 2026-10-02 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='resume_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
