# Generated by Django 5.2.17 on 2026-10-03 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0002_analysis_resume_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='resume_hash',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
    ]
