# Generated by Django 5.2.17 on 2026-10-04 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0004_alter_analysis_options_loginevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='matched_keywords',
            field=models.JSONField(default=list),
        ),
    ]
