import { LABELS, MAXES, PRIORITY, fmt, normSuggestions, summaryText } from "./utils.js";

const esc = (s) => String(s ?? "").replace(/[&<>"]/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" }[c]));

// Opens a clean report in a new tab and starts printing: choose "Save as PDF" in the print window.
export function downloadReport(r, user) {
  const w = window.open("", "_blank");
  if (!w) { alert("Please allow pop-ups for this site to download the report."); return; }
  const rows = Object.entries(r.ats_breakdown || {}).map(([k, v]) => `<tr><td>${esc(LABELS[k] || k)}</td><td class="r">${esc(v)}/${MAXES[k] || 10}</td></tr>`).join("");
  const chips = (list, cls) => (list.length ? list.map((k) => `<span class="chip ${cls}">${esc(k)}</span>`).join("") : "<i>None</i>");
  const sug = normSuggestions(r.suggestions);
  const sugHtml = ["high", "medium", "low"].map((p) => {
    const items = sug.filter((s) => s.priority === p);
    return items.length ? `<h4>${PRIORITY[p][0]} ${PRIORITY[p][1]}</h4><ul>${items.map((s) => `<li>${esc(s.text)}</li>`).join("")}</ul>` : "";
  }).join("");
  w.document.write(`<!doctype html><html><head><meta charset="utf-8"><title>Chayan report - ${esc(r.resume_name)}</title><style>
body{font-family:Arial,Helvetica,sans-serif;color:#0f172a;max-width:760px;margin:24px auto;padding:0 20px;line-height:1.5}
.hd{background:linear-gradient(135deg,#4f46e5,#9333ea,#ec4899);color:#fff;padding:22px;border-radius:14px;-webkit-print-color-adjust:exact;print-color-adjust:exact}
.hd h1{margin:0;font-size:28px}.hd p{margin:4px 0 0;opacity:.9}h2{margin:26px 0 8px;font-size:18px;border-bottom:2px solid #e2e8f0;padding-bottom:4px}
.scores{display:flex;gap:16px}.box{flex:1;border:1px solid #e2e8f0;border-radius:12px;padding:14px;text-align:center}.box b{display:block;font-size:34px;color:#4f46e5}
table{width:100%;border-collapse:collapse}td{padding:6px 0;border-bottom:1px solid #f1f5f9}.r{text-align:right;font-weight:700}
.chip{display:inline-block;margin:3px;padding:3px 10px;border-radius:999px;font-size:12px}.ok{background:#d1fae5;color:#065f46}.bad{background:#fee2e2;color:#991b1b}
li{margin:4px 0}.ft{margin-top:30px;color:#94a3b8;font-size:12px;text-align:center}
</style></head><body>
<div class="hd"><h1>Chayan</h1><p>Analyze. Match. Get Selected.</p></div>
<h2>Resume report</h2>
<p><b>Resume:</b> ${esc(r.resume_name || "Resume")}<br><b>Date:</b> ${esc(fmt(r.created_at))}${user ? `<br><b>Prepared for:</b> ${esc(user.name)}` : ""}</p>
<div class="scores"><div class="box"><b>${Math.round(r.match_score)}%</b>Match score</div><div class="box"><b>${Math.round(r.ats_score)}%</b>ATS score</div></div>
<p>${esc(summaryText(r))}</p>
<h2>ATS breakdown</h2><table>${rows}</table>
<h2>Matched skills</h2>${chips(r.matched_keywords || [], "ok")}
<h2>Missing keywords</h2>${chips((r.missing_keywords || []).map((m) => m.keyword), "bad")}
<h2>Improvement suggestions</h2>${sugHtml}
<div class="ft">Generated by Chayan. Scores are estimates from keyword matching and rule-based checks, not a guarantee of selection.</div>
</body></html>`);
  w.document.close();
  w.focus();
  setTimeout(() => w.print(), 400);
}
